export type PracticeQuestion = {
  question: string
  answer: string
  options: string[]
  explanation?: string
  subtopic?: string
  difficulty?: 'beginner' | 'intermediate' | 'advanced'
}

export const CS_TOPICS: { key: string; label: string }[] = [
  { key: 'os', label: 'Operating Systems' },
  { key: 'dbms', label: 'DBMS' },
  { key: 'technical', label: 'Technical Quiz' },
  { key: 'technical2', label: 'Technical Quiz 2' },
]

const q = (
  question: string,
  options: string[],
  answer: string,
  explanation?: string,
  subtopic?: string,
  difficulty?: 'beginner' | 'intermediate' | 'advanced'
): PracticeQuestion => ({ question, options, answer, explanation, subtopic, difficulty })

export const CS_QUESTIONS: Record<string, PracticeQuestion[]> = {
  os: [
    q('Which scheduling is non-preemptive?', ['Round Robin', 'Priority', 'FCFS', 'SRTF'], 'FCFS', '', 'Scheduling', 'beginner'),
    q('Which is a deadlock condition?', ['Mutual exclusion', 'No preemption', 'Hold and wait', 'All of these'], 'All of these', '', 'Deadlock', 'intermediate'),
    q('Page size selection affects?', ['Fragmentation', 'TLB hit', 'Context switch', 'All'], 'All', '', 'Memory Management', 'intermediate'),
    q('Thrashing is due to?', ['High CPU', 'Low I/O', 'High page fault', 'Large quantum'], 'High page fault', '', 'Paging', 'intermediate'),
    q('Segmented memory divides by?', ['Fixed size', 'Variable length', 'Pages only', 'Cache lines'], 'Variable length', '', 'Segmentation', 'beginner'),
    q('Which is not a disk scheduling?', ['SCAN', 'LOOK', 'C-SCAN', 'LRU'], 'LRU', '', 'Disk Scheduling', 'beginner'),
    q('Critical section solved by?', ['Semaphores', 'Paging', 'Segmentation', 'DMA'], 'Semaphores', '', 'Synchronization', 'intermediate'),
    q('Producer-consumer uses?', ['Mutex only', 'Semaphore', 'Paging', 'Pipes'], 'Semaphore', '', 'IPC', 'intermediate'),
    q('Kernel mode allows?', ['Privileged instructions', 'User I/O only', 'No interrupts', 'None'], 'Privileged instructions', '', 'OS Modes', 'beginner'),
    q('Context switch saves?', ['PCB', 'TLB only', 'Cache only', 'None'], 'PCB', '', 'Processes', 'beginner'),
  ],
  dbms: [
    q('Normalization reduces?', ['Anomalies', 'Indexes', 'Transactions', 'Joins'], 'Anomalies', '', 'Normalization', 'beginner'),
    q('Which normal form removes partial dependency?', ['1NF', '2NF', '3NF', 'BCNF'], '2NF', '', 'Normalization', 'beginner'),
    q('ACID: I stands for?', ['Isolation', 'Integration', 'Iteration', 'Index'], 'Isolation', '', 'Transactions', 'beginner'),
    q('Which is non-clustered index?', ['Primary key', 'Secondary index', 'Cluster key', 'Heap'], 'Secondary index', '', 'Indexing', 'intermediate'),
    q('Transaction schedule serializable means?', ['Equivalent to a serial order', 'Parallel always', 'Faster', 'Lock-free'], 'Equivalent to a serial order', '', 'Concurrency Control', 'intermediate'),
    q('View is?', ['Virtual table', 'Materialized table', 'Physical file', 'Index'], 'Virtual table', '', 'Views', 'beginner'),
    q('Foreign key ensures?', ['Entity integrity', 'Referential integrity', 'Domain integrity', 'None'], 'Referential integrity', '', 'Constraints', 'beginner'),
    q('BCNF stronger than?', ['3NF', '2NF', '1NF', 'Dknf'], '3NF', '', 'Normalization', 'intermediate'),
    q('SQL to remove table?', ['DROP TABLE T', 'DELETE TABLE T', 'REMOVE T', 'TRUNCATE DATABASE'], 'DROP TABLE T', '', 'SQL DDL', 'beginner'),
    q('Which isolation level is strictest?', ['Read uncommitted', 'Read committed', 'Repeatable read', 'Serializable'], 'Serializable', '', 'Isolation Levels', 'advanced'),
  ],
  technical: [
    q(
      `What is the output of this code?\npublic class RecursionGame {\n static int solve(int n) { if (n == 0) return 0; return solve(n / 2) + n % 2; }\n public static void main(String[] args) { System.out.println(solve(255)); }\n}`,
      ['8', '7', '6', '5'],
      '8',
      '',
      'Recursion / Bit Count',
      'intermediate',
    ),
    q(
      `What will be the output of the following Java code?\npublic class RecTest {\n static int fun(int n) { if (n <= 0) return 0; if (n % 2 == 0) return fun(n - 1) + n; else return fun(n - 2) + n; }\n public static void main(String[] args) { System.out.println(fun(6)); }\n}`,
      ['15', '21', '12', '18'],
      '21',
      '',
      'Recursion / Even-Odd',
      'intermediate',
    ),
    q(
      `What is the output of this recursive code with bitwise XOR?\npublic class BitXorRec {\n static int xorMagic(int n) { if (n == 0) return 0; return n ^ xorMagic(n - 1); }\n public static void main(String[] args) { System.out.println(xorMagic(5)); }\n}`,
      ['0', '1', '2', '3'],
      '2',
      '',
      'Recursion / Bitwise XOR',
      'intermediate',
    ),
    q(
      `Output of the following recursion logic?\npublic class BinaryLike {\n static void printPattern(int n, String s) { if (n == 0) { System.out.print(s + " "); return; } printPattern(n - 1, s + "0"); printPattern(n - 1, s + "1"); }\n public static void main(String[] args) { printPattern(3, ""); }\n}`,
      [
        'All binary numbers from 0 to 7',
        '000 001 010 011 100',
        '000 001 010 011 100 101 110 111',
        'All permutations of 3 digits',
      ],
      '000 001 010 011 100 101 110 111',
      '',
      'Recursion / Binary Patterns',
      'intermediate',
    ),
    q(
      `What will this print?\npublic class Test {\n static void change(String s) { s = s.concat(" World"); }\n public static void main(String[] args) { String str = "Hello"; change(str); System.out.println(str); }\n}`,
      ['Hello', 'Hello world', 'world', 'null'],
      'Hello',
      '',
      'Java Strings / Immutability',
      'beginner',
    ),
    q(
      `What is the output of this queue simulation?\nQueue q = new LinkedList(); q.add(1); q.add(2); q.add(3); q.remove(); q.add(4); System.out.println(q);`,
      ['[2,3,4]', '[1,2,3,4]', '[1,3,4]', '[3,4]'],
      '[2,3,4]',
      '',
      'Java Collections / Queue',
      'beginner',
    ),
    q(
      `What is the output of this array manipulation code?\nimport java.util.Arrays;\npublic class Test { public static void main(String[] args) { int[] arr = {1, 2, 3, 4}; for (int i = 0; i < arr.length; i++) { arr[i] = arr[(i + 1) % arr.length]; } System.out.println(Arrays.toString(arr)); } }`,
      ['[2,3,4,1]', '[2,3,4,2]', '[2,3,4,4]', '[1,2,3,4]'],
      '[2,3,4,1]',
      '',
      'Java Arrays / Mod Index',
      'intermediate',
    ),
    q(
      `What does this print?\npublic class Test { public static void change(StringBuilder sb) { sb.append(" world"); } public static void main(String[] args) { StringBuilder sb = new StringBuilder("Hello"); change(sb); System.out.println(sb); } }`,
      ['Hello', 'Hello world', 'world', 'compilation error'],
      'Hello world',
      '',
      'Java StringBuilder / Mutability',
      'beginner',
    ),
    q(
      `What will this stack-based code output?\npublic static void main(String[] args) { Stack stack = new Stack(); stack.push(10); stack.push(20); System.out.println(stack.peek()); stack.pop(); System.out.println(stack.peek()); }`,
      ['20 10', '10 20', '20 20', 'exception'],
      '20 10',
      '',
      'Java Stack',
      'beginner',
    ),
    q(
      `public int func(int n) { if (n <= 1) return 1; return func(n - 1) + func(n - 2); }`,
      ['O(n)', 'O(n^2)', 'O(2^n)', 'O(log n)'],
      'O(2^n)',
      '',
      'Time Complexity / Recurrence',
      'intermediate',
    ),
    q(
      'Which interface is implemented by all collection classes in Java?',
      ['Map', 'Collection', 'Iterator', 'Set'],
      'Collection',
      '',
      'Java Collections',
      'beginner',
    ),
    q(
      'Which keyword is used to access the parent class members in Java?',
      ['parent', 'this', 'super', 'base'],
      'super',
      '',
      'Java OOP / Inheritance',
      'beginner',
    ),
    q(
      'Which keyword is used by a class to implement an interface?',
      ['interface', 'inherit', 'implements', 'extends'],
      'implements',
      '',
      'Java Interfaces',
      'beginner',
    ),
    q(
      'Which of the following can an interface contain?',
      ['Instance variables', 'Constructors', 'Abstract methods and constants', 'Static blocks'],
      'Abstract methods and constants',
      '',
      'Java Interfaces',
      'beginner',
    ),
    q(
      'What is the size of int in Java?',
      ['2 bytes', '4 bytes', '8 bytes', 'Depends on OS'],
      '4 bytes',
      '',
      'Java Types',
      'beginner',
    ),
    q(
      'Which operator is used to check if two objects are the same reference?',
      ['==', 'equals()', 'compareTo()', 'instanceOf'],
      '==',
      '',
      'Java Equality / References',
      'beginner',
    ),
    q(
      'Which keyword is used to create an object in Java?',
      ['new', 'class', 'object', 'create'],
      'new',
      '',
      'Java Object Creation',
      'beginner',
    ),
    q(
      'What will be the output? java String s = "Java"; System.out.println(s.toUpperCase());',
      ['java', 'JAVA', 'error', 'null'],
      'JAVA',
      '',
      'Java Strings',
      'beginner',
    ),
    q(
      'Which of the following methods is defined in the Object class?',
      ['compareTo()', 'equals()', 'length()', 'substring()'],
      'equals()',
      '',
      'Java Object Class',
      'beginner',
    ),
    q(
      'Which of these operators is used for string concatenation in Java?',
      ['+', '&', '.', 'concat'],
      '+',
      '',
      'Java Operators',
      'beginner',
    ),
    q(
      'What is the output of print(2**3)?',
      ['6', '8', '9', 'Error'],
      '8',
      '',
      'Python Operators / Exponent',
      'beginner',
    ),
    q(
      'What is the output of print(type(3.14))?',
      ["<class 'int'>", "<class 'str'>", "<class 'float'>", "<class 'list'>"],
      "<class 'float'>",
      '',
      'Python Types',
      'beginner',
    ),
    q(
      "What is the output of print('Python'[:2])?",
      ['Py', 'Pyt', 'on', 'Error'],
      'Py',
      '',
      'Python Slicing',
      'beginner',
    ),
    q(
      "What is the data type of: x = 'Hello'?",
      ['int', 'str', 'list', 'dict'],
      'str',
      '',
      'Python Types',
      'beginner',
    ),
    q(
      'What will print(5%2) return?',
      ['2.5', '1', '0', '2'],
      '1',
      '',
      'Python Operators / Modulo',
      'beginner',
    ),
    q(
      'What will print(10//3) return in Python?',
      ['3.33', '3', '4', 'Error'],
      '3',
      '',
      'Python Operators / Floor Division',
      'beginner',
    ),
    q(
      'Which of the following is an immutable data type in Python?',
      ['list', 'tuple', 'dict', 'set'],
      'tuple',
      '',
      'Python Types / Immutability',
      'beginner',
    ),
    q(
      "What is the output of print(bool('False'))?",
      ['False', 'True', 'Error', 'None'],
      'True',
      '',
      'Python bool() / Truthiness',
      'beginner',
    ),
    q(
      'Which method adds an element to the end of a Python list?',
      ['add()', 'append()', 'insert()', 'extend()'],
      'append()',
      '',
      'Python Lists / Methods',
      'beginner',
    ),
    q(
      'What is the output of print(len([1, 2, 3, 4]))?',
      ['3', '4', '5', 'Error'],
      '4',
      '',
      'Python Lists / len()',
      'beginner',
    ),
    q(
      'Which of these is used to define a function in Python?',
      ['def', 'func', 'function', 'lambda'],
      'def',
      '',
      'Python Functions / def',
      'beginner',
    ),
    q(
      "What does '//' operator do in Python?",
      ['Division', 'Floor Division', 'Modulo', 'Exponent'],
      'Floor Division',
      '',
      'Python Operators / Floor Division',
      'beginner',
    ),
    q(
      'Which of these data types is mutable in Python?',
      ['tuple', 'str', 'list', 'frozenset'],
      'list',
      '',
      'Python Types / Mutability',
      'beginner',
    ),
    q(
      "What is the output of print(2 * 'Hi')?",
      ['HiHi', 'Hi Hi', 'Error', '2Hi'],
      'HiHi',
      '',
      'Python Strings / Repetition',
      'beginner',
    ),
    q(
      'Which of the following is used for comments in Python?',
      ['//', '/* */', '#', ''],
      '#',
      '',
      'Python Syntax / Comments',
      'beginner',
    ),
    q(
      'Which of these is a valid variable name in Python?',
      ['1var', '_var', 'var-1', 'var 1'],
      '_var',
      '',
      'Python Variables / Naming',
      'beginner',
    ),
    q(
      'Which Python keyword is used for conditional branching?',
      ['if', 'for', 'while', 'break'],
      'if',
      '',
      'Python Control Flow / if',
      'beginner',
    ),
    q(
      'What is the output of print([1,2]+[3,4])?',
      ['[1,2,3,4]', '[1,2][3,4]', '[1,2, 3,4]', 'Error'],
      '[1,2,3,4]',
      '',
      'Python Lists / Concatenation',
      'beginner',
    ),
    q(
      'What is the output of print(10%3)?',
      ['3', '1', '0', 'Error'],
      '1',
      '',
      'Python Operators / Modulo',
      'beginner',
    ),
    q(
      'Which method removes the last item from a Python list?',
      ['remove()', 'pop()', 'del()', 'discard()'],
      'pop()',
      '',
      'Python Lists / pop()',
      'beginner',
    ),
    q(
      'What is the output of print(bool([]))?',
      ['True', 'False', 'Error', 'None'],
      'False',
      '',
      'Python Truthiness / Empty List',
      'beginner',
    ),
    q(
      'What is the output of print(5**2)?',
      ['25', '10', '7', 'Error'],
      '25',
      '',
      'Python Operators / Exponent',
      'beginner',
    ),
    q(
      'Which keyword is used to handle exceptions in Python?',
      ['try', 'catch', 'except', 'error'],
      'except',
      '',
      'Python Exceptions',
      'beginner',
    ),
    q(
      'Which of these is used to create an empty set in Python?',
      ['{}', '[]', 'set()', '()'],
      'set()',
      '',
      'Python Sets / Creation',
      'beginner',
    ),
    q(
      'Which keyword is used to define an anonymous function in Python?',
      ['def', 'lambda', 'function', 'anon'],
      'lambda',
      '',
      'Python Functions / lambda',
      'beginner',
    ),
    q(
      "What is the output of print(list('Python'))?",
      ["['P','y','t','h','o','n']", "['Python']", "['P','y','t','h','o']", 'Error'],
      "['P','y','t','h','o','n']",
      '',
      'Python Lists / list() on String',
      'beginner',
    ),
    q(
      'Which of these is a tuple in Python?',
      ['(1,2,3)', '[1,2,3]', '{1,2,3}', 'None'],
      '(1,2,3)',
      '',
      'Python Tuples',
      'beginner',
    ),
    q(
      'Which of these is the correct way to import the math module?',
      ['import math', 'include math', '#import math', 'using math'],
      'import math',
      '',
      'Python Imports',
      'beginner',
    ),
    q(
      'Which of these converts a string to an integer in Python?',
      ['int()', 'str()', 'float()', 'eval()'],
      'int()',
      '',
      'Python Casting / int()',
      'beginner',
    ),
    q(
      "What will print('Hello' + str(5)) output?",
      ['Hello5', 'Hello 5', 'Error', '5Hello'],
      'Hello5',
      '',
      'Python Strings + Numbers',
      'beginner',
    ),
  ],
  technical2: [
    q(
      "What will print(type([])) return in Python?",
      ["<class 'list'>", "<class 'tuple'>", "<class 'dict'>", "<class 'set'>"],
      "<class 'list'>",
      '',
      'Python Types / list',
      'beginner',
    ),
    q(
      'Which of these is a valid Python loop?',
      ['for i in range(5):', 'foreach i in range(5):', 'loop i in range(5):', 'for i=0; i<5; i++:'],
      'for i in range(5):',
      '',
      'Python Loops / for',
      'beginner',
    ),
    q(
      "What is the output of print('a' * 5)?",
      ['aaaaa', 'a a a a a', 'Error', '5a'],
      'aaaaa',
      '',
      'Python Strings / Repetition',
      'beginner',
    ),
    q(
      'Which method can remove a specific item from a Python list?',
      ['pop()', 'remove()', 'discard()', 'delete()'],
      'remove()',
      '',
      'Python Lists / remove()',
      'beginner',
    ),
    q(
      'What is the output of print(7//2)?',
      ['3', '3.5', '4', 'Error'],
      '3',
      '',
      'Python Operators / Floor Division',
      'beginner',
    ),
    q(
      'Which of the following is the correct syntax to define a dictionary in Python?',
      ["{ 'a': 1, 'b': 2 }", "[ 'a':1, 'b':2 ]", "( 'a':1, 'b':2 )", '{ a=1, b=2 }'],
      "{ 'a': 1, 'b': 2 }",
      '',
      'Python Dicts / Syntax',
      'beginner',
    ),
    q(
      'Which of the following statements is true for Python sets?',
      ['Sets are ordered', 'Sets allow duplicates', 'Sets are mutable but unordered', 'Sets are immutable'],
      'Sets are mutable but unordered',
      '',
      'Python Sets / Properties',
      'beginner',
    ),
    q(
      'Which operator is used for exponentiation in Python?',
      ['^', '**', '%', '//'],
      '**',
      '',
      'Python Operators / Exponent',
      'beginner',
    ),
    q(
      "What is the output of print('Python'[-1])?",
      ['P', 'n', 'o', 'Error'],
      'n',
      '',
      'Python Strings / Indexing',
      'beginner',
    ),
    q(
      "What will print(3*'ab') output?",
      ['ababab', 'ab ab ab', 'Error', '3ab'],
      'ababab',
      '',
      'Python Strings / Repetition',
      'beginner',
    ),
    q(
      'Which of the following keywords is used for loops in Python?',
      ['for', 'loop', 'repeat', 'whiledo'],
      'for',
      '',
      'Python Loops / for',
      'beginner',
    ),
    q(
      'Which of these keywords is used to exit a loop in Python?',
      ['exit', 'break', 'stop', 'return'],
      'break',
      '',
      'Python Loops / break',
      'beginner',
    ),
    q(
      'Which of the following is true about Python functions?',
      ['Functions cannot return values', 'Functions can return multiple values', 'Functions must have parameters', 'Functions cannot be nested'],
      'Functions can return multiple values',
      '',
      'Python Functions / Return',
      'beginner',
    ),
    q(
      'What will print(5%2) output?',
      ['2', '1', '0', 'Error'],
      '1',
      '',
      'Python Operators / Modulo',
      'beginner',
    ),
    q(
      'Which of the following is used to comment multiple lines in Python?',
      ['//', '/* /', '""" """', '#'],
      '""" """',
      '',
      'Python Comments / Multiline',
      'beginner',
    ),
    q(
      'Which method returns the number of items in a Python list?',
      ['size()', 'length()', 'len()', 'count()'],
      'len()',
      '',
      'Python Lists / len()',
      'beginner',
    ),
    q(
      'What is the output of print(type(5/2))?',
      ['int', 'float', 'str', 'complex'],
      'float',
      '',
      'Python Types / Division',
      'beginner',
    ),
    q(
      "What is the output of print('abc' + 'def')?",
      ['abcdef', 'abc def', 'abc+def', 'Error'],
      'abcdef',
      '',
      'Python Strings / Concatenation',
      'beginner',
    ),
    q(
      'Which of these can be used to create a Python list?',
      ['[]', '()', '{}', '<>'],
      '[]',
      '',
      'Python Lists / Creation',
      'beginner',
    ),
    q(
      'Which of these will raise a TypeError in Python?',
      ['3 + 4', "'3' + '4'", "3 + '4'", '32'],
      "3 + '4'",
      '',
      'Python Errors / TypeError',
      'beginner',
    ),
    q(
      'Which method can be used to convert a string to lowercase in Python?',
      ['lower()', 'uppercase()', 'tolower()', 'toLowerCase()'],
      'lower()',
      '',
      'Python Strings / lower()',
      'beginner',
    ),
    q(
      'Which Python keyword is used to continue to the next iteration in a loop?',
      ['continue', 'next', 'skip', 'pass'],
      'continue',
      '',
      'Python Loops / continue',
      'beginner',
    ),
    q(
      'Which of the following is used to check membership in Python?',
      ['in', 'include', 'has', 'with'],
      'in',
      '',
      'Python Operators / in',
      'beginner',
    ),
    q(
      'Which method adds elements from one list to another in Python?',
      ['append()', 'extend()', 'insert()', 'add()'],
      'extend()',
      '',
      'Python Lists / extend()',
      'beginner',
    ),
    q(
      'Which of these is the correct way to handle exceptions in Python?',
      ['try-except', 'try-catch', 'try-finally', 'catch-try'],
      'try-except',
      '',
      'Python Exceptions / try-except',
      'beginner',
    ),
    q(
      'Which of the following is a valid Python boolean value?',
      ['True', 'true', 'TRUE', 't'],
      'True',
      '',
      'Python Types / bool',
      'beginner',
    ),
    q(
      'What is the output of print(0.1 + 0.2 == 0.3)?',
      ['True', 'False', 'Error', 'None'],
      'False',
      '',
      'Python Floats / Precision',
      'beginner',
    ),
    q(
      'Which of the following is used to read input from the user in Python?',
      ['input()', 'read()', 'scanf()', 'cin'],
      'input()',
      '',
      'Python I/O / input()',
      'beginner',
    ),
    q(
      'What is the output of print(list(range(3)))?',
      ['[0,1,2]', '[1,2,3]', '[0,1,2,3]', 'Error'],
      '[0,1,2]',
      '',
      'Python range()',
      'beginner',
    ),
    q(
      'Which of the following is a valid Python float value?',
      ['3.14', '3,14', 'pi', '314'],
      '3.14',
      '',
      'Python Types / float',
      'beginner',
    ),
    q(
      'Which of the following data types is immutable in Python?',
      ['list', 'set', 'tuple', 'dict'],
      'tuple',
      '',
      'Python Types / Immutability',
      'beginner',
    ),
    q(
      'What will print(type({})) return?',
      ['dict', 'set', 'list', 'tuple'],
      'dict',
      '',
      'Python Types / dict',
      'beginner',
    ),
    q(
      'Which of these operators is used for modulo in Python?',
      ['%', '//', '', 'mod'],
      '%',
      '',
      'Python Operators / Modulo',
      'beginner',
    ),
    q(
      "What is the output of print('Python'[1:4])?",
      ['Pyt', 'yth', 'ytho', 'Py'],
      'yth',
      '',
      'Python Strings / Slicing',
      'beginner',
    ),
    q(
      'Which of these is the correct way to comment a single line in Python?',
      ['// comment', '# comment', '/* comment */', ''],
      '# comment',
      '',
      'Python Comments / Single Line',
      'beginner',
    ),
    q(
      'Which Python keyword is used to exit a function and return a value?',
      ['exit', 'return', 'break', 'yield'],
      'return',
      '',
      'Python Functions / return',
      'beginner',
    ),
    q(
      'Which of these statements creates an empty dictionary in Python?',
      ['{}', '[]', '()', 'dict[]'],
      '{}',
      '',
      'Python Dicts / Empty',
      'beginner',
    ),
    q(
      'What is the output of print(10 > 5 and 5 < 3)?',
      ['True', 'False', 'Error', 'None'],
      'False',
      '',
      'Python Booleans / and',
      'beginner',
    ),
    q(
      'Which of these is the correct way to define a class in Python?',
      ['class MyClass:', 'class MyClass()', 'def MyClass:', 'define MyClass:'],
      'class MyClass:',
      '',
      'Python OOP / class',
      'beginner',
    ),
    q(
      'Which of these is the correct way to handle exceptions in Python?',
      ['try-except', 'try-catch', 'try-finally', 'catch-try'],
      'try-except',
      '',
      'Python Exceptions / try-except',
      'beginner',
    ),
    q(
      'Which of the following is used to add an element to a set in Python?',
      ['add()', 'append()', 'insert()', 'extend()'],
      'add()',
      '',
      'Python Sets / add()',
      'beginner',
    ),
    q(
      'Which of these is true about Python lists?',
      ['Lists are immutable', 'Lists are ordered and mutable', 'Lists are unordered', 'Lists are immutable and unordered'],
      'Lists are ordered and mutable',
      '',
      'Python Lists / Properties',
      'beginner',
    ),
    q(
      'Which of the following will raise an error?',
      ['5 + 3', "'5' + '3'", "5 + '3'", '5 * 3'],
      "5 + '3'",
      '',
      'Python Errors / TypeError',
      'beginner',
    ),
    q(
      'Which of these is a valid Python string method?',
      ['upper()', 'uppercase()', 'toUpper()', 'toupper()'],
      'upper()',
      '',
      'Python Strings / upper()',
      'beginner',
    ),
    q(
      'Which Python keyword is used to define a generator?',
      ['generate', 'yield', 'return', 'gen'],
      'yield',
      '',
      'Python Generators / yield',
      'beginner',
    ),
    q(
      'Which operator is used for integer division in Python?',
      ['/', '//', '%', ''],
      '//',
      '',
      'Python Operators / Integer Division',
      'beginner',
    ),
    q(
      'Which of the following creates a tuple with one element?',
      ['(5,)', '(5)', '[5]', '{5}'],
      '(5,)',
      '',
      'Python Tuples / Single Element',
      'beginner',
    ),
    q(
      'Which of these will output True?',
      ['3 in [1,2,3]', "'a' in 'abc'", '5 > 2', 'All of the above'],
      'All of the above',
      '',
      'Python Booleans / Membership',
      'beginner',
    ),
    q(
      'Which of these is used to stop a loop iteration and continue with next iteration in Python?',
      ['break', 'continue', 'pass', 'exit'],
      'continue',
      '',
      'Python Loops / continue',
      'beginner',
    ),
    q(
      'Which of the following converts an integer to a string in Python?',
      ['str()', 'int()', 'float()', 'toString()'],
      'str()',
      '',
      'Python Casting / str()',
      'beginner',
    ),
  ],
}

// Ensure defaults for metadata
const CS_DEFAULTS: Record<string, { subtopic: string; difficulty: 'beginner'|'intermediate'|'advanced' }[]> = {
  os: new Array(10).fill(0).map(() => ({ subtopic: 'OS - General', difficulty: 'beginner' })),
  dbms: new Array(10).fill(0).map(() => ({ subtopic: 'DBMS - General', difficulty: 'beginner' })),
  technical: new Array(50).fill(0).map(() => ({ subtopic: 'Technical Quiz - General', difficulty: 'beginner' })),
  technical2: new Array(50).fill(0).map(() => ({ subtopic: 'Technical Quiz 2 - General', difficulty: 'beginner' })),
}

for (const topic of Object.keys(CS_QUESTIONS)) {
  const arr = CS_QUESTIONS[topic]
  const defs = (CS_DEFAULTS as any)[topic] || []
  CS_QUESTIONS[topic] = arr.map((q, i) => ({
    ...q,
    subtopic: q.subtopic || defs[i]?.subtopic || `${topic} - General`,
    difficulty: q.difficulty || defs[i]?.difficulty || 'beginner',
  }))
}
